parameters:
  - name: serviceConnection
    type: string
    # values:
    #   - $(serviceConnection_dev)
    #   - $(serviceConnection_test)
    #   - $(serviceConnection_preprod)
    #   - $(serviceConnection_prod)
    #   - $(serviceConnection_shared)


  - name: environment
    type: string
    values:
      - dev
      - test
      - preprod
      - prod
      - shared
      
  - name: location
    type: string
    default: "westeurope"

  - name: mainTemplate
    type: string
    default: "main.bicep"

  - name: resourceGroupName
    type: string

  - name: additionalArguments
    type: string
    default: "--out yamlc --no-prompt"

jobs:
  - job: "Validate"
    displayName: Validate ${{ parameters.resourceGroupName }}
    pool:
      name: $(agentPool)
    steps:
      - template: ../tasks/bicep-lint.yml
        parameters:
          mainTemplate: ${{ parameters.mainTemplate }}
          skipTests: 'DeploymentTemplate Must Not Contain Hardcoded Uri'

      - template: ../tasks/az-deploy.yml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
          mainTemplate: $(templatelocation)/${{ parameters.mainTemplate }}
          resourceGroupName: ${{ parameters.resourceGroupName }}
          environment: ${{ parameters.environment }}
          additionalArguments: ${{ parameters.additionalArguments }}
          command: "validate"
      - template: ../tasks/defender.yml
      - template: ../tasks/az-deploy.yml
        parameters:
          serviceConnection: ${{ parameters.serviceConnection }}
          mainTemplate: $(templatelocation)/${{ parameters.mainTemplate }}
          resourceGroupName: ${{ parameters.resourceGroupName }}
          environment: ${{ parameters.environment }}
          additionalArguments: ${{ parameters.additionalArguments }}
          command: "what-if"
