# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
    - ChatCIB
  branches:
    include:
    - main


pool:
  name: AzureDeploy


variables:
- template: ../.azure-pipelines/variables.yml
  parameters:
    teamName: chatcib
- name: devResourceGroup
  value: 'rg-chatcib-dev-weu'
- name: testResourceGroup
  value: 'rg-chatcib-test-weu'
- name: preprodResourceGroup
  value: 'rg-chatcib-preprod-weu'
- name: prodResourceGroup
  value: 'rg-chatcib-prod-weu'
stages:
- stage: "Validate"
  displayName: Validate
  jobs:
    - template: ../.azure-pipelines/jobs/bicep-validate.yml

      parameters:
        serviceConnection: $(serviceConnection_dev)
        resourceGroupName: $(devResourceGroup)
        environment: dev
        mainTemplate: ./ChatCIB/main.bicep

- stage: "DeployDev"
  displayName: "Deploy to dev"
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - template: ../.azure-pipelines/jobs/bicep-deploy.yml
    parameters:
      environment: dev
      serviceConnection: $(serviceConnection_dev)
      resourceGroupName: $(devResourceGroup)
      mainTemplate: ./ChatCIB/main.bicep

# - stage: "DeployTest"
#   displayName: "Deploy to test"
#   condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
#   jobs:
#   - template: ../.azure-pipelines/jobs/bicep-deploy.yml
#     parameters:
#       environment: test
#       serviceConnection: $(serviceConnection_test)
#       resourceGroupName: $(testResourceGroup)
#       mainTemplate: ./ChatCIB/main.bicep

# - stage: "DeployPreprod"
#   displayName: "Deploy to preprod"
#   condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
#   jobs:
#   - template: ../.azure-pipelines/jobs/bicep-deploy.yml
#     parameters:
#       environment: preprod
#       serviceConnection: $(serviceConnection_preprod)
#       resourceGroupName: $(preprodResourceGroup)
#       mainTemplate: ./ChatCIB/main.bicep

- stage: "DeployProd"
  displayName: "Deploy to prod"
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  jobs:
  - template: ../.azure-pipelines/jobs/bicep-deploy.yml
    parameters:
      environment: prod
      serviceConnection: $(serviceConnection_prod)
      resourceGroupName: $(prodResourceGroup)
      mainTemplate: ./ChatCIB/main.bicep
