# parameters:
#   - name: failPipelineOnFailingTests
#     type: string

steps:
  - task: UseDotNet@2
    displayName: 'Use dotnet'
    inputs:
      version: 5.0.x
  - task: UseDotNet@2
    displayName: 'Use dotnet'
    inputs:
      version: 6.0.x
  - task: UseDotNet@2
    displayName: 'Use dotnet'
    inputs:
      version: 8.0.x
  - task: MicrosoftSecurityDevOps@1
    displayName: 'Microsoft Security DevOps'
    inputs:
      break: false
      categories: 'IaC, containers'
      # tools: 'iacfilescanner, templateanalyzer, trivy, terrascan'