trigger:
  paths:
    include:
      - CLM
  branches:
    include:
      - main

pool:
  name: AzureDeploy

variables:
  - template: ../.azure-pipelines/variables.yml
    parameters:
      teamName: clm
  - name: devResourceGroup
    value: 'rg-clm-dev-weu'
  - name: testResourceGroup
    value: 'rg-clm-test-weu'
  - name: preprodResourceGroup
    value: 'rg-clm-preprod-weu'
  - name: prodResourceGroup
    value: 'rg-clm-prod-weu'
stages:  
  - stage: "Validate"
    displayName: Validate
    jobs:
      - template: ../.azure-pipelines/jobs/bicep-validate.yml
        parameters:
          serviceConnection: $(serviceConnection_dev)
          resourceGroupName: $(devResourceGroup)
          environment: dev
          mainTemplate: ./CLM/main.bicep
          additionalArguments:  --parameters ./CLM/parameters.dev.json

  - stage: "DeployDev"
    displayName: "Deploy to dev"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: ../.azure-pipelines/jobs/bicep-deploy.yml
        parameters:
          environment: dev
          serviceConnection: $(serviceConnection_dev)
          resourceGroupName:  $(devResourceGroup)
          mainTemplate: ./CLM/main.bicep
          additionalArguments:  --parameters ./CLM/parameters.dev.json
 
  - stage: "DeployTest"
    displayName: "Deploy to test"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: ../.azure-pipelines/jobs/bicep-deploy.yml
        parameters:
          environment: test
          serviceConnection: $(serviceConnection_test)
          resourceGroupName:  $(testResourceGroup)
          mainTemplate: ./CLM/main.bicep
          additionalArguments:  --parameters ./CLM/parameters.test.json
  
  - stage: "DeployPreprod"
    displayName: "Deploy to preprod"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: ../.azure-pipelines/jobs/bicep-deploy.yml
        parameters:
          environment: preprod
          serviceConnection: $(serviceConnection_preprod)
          resourceGroupName:  $(preprodResourceGroup)
          mainTemplate: ./CLM/main.bicep
          additionalArguments:  --parameters ./CLM/parameters.preprod.json

  - stage: "DeployProd"
    displayName: "Deploy to prod"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: ../.azure-pipelines/jobs/bicep-deploy.yml
        parameters:
          environment: prod
          serviceConnection: $(serviceConnection_prod)
          resourceGroupName:  $(prodResourceGroup)
          mainTemplate: ./CLM/main.bicep
          additionalArguments:  --parameters ./CLM/parameters.prod.json
