# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
      - Infrastructure
  branches:
    include:
      - main

pool:
  name: AzureDeploy

variables:
  - template: ../.azure-pipelines/variables.yml
    parameters:
      teamName: infrastructure
  - name: devResourceGroup
    value: 'rg-infrastructure-dev-weu'
  - name: testResourceGroup
    value: 'rg-infrastructure-test-weu'
  - name: preprodResourceGroup
    value: 'rg-infrastructure-preprod-weu'
  - name: prodResourceGroup
    value: 'rg-infrastructure-prod-weu'
stages:
  - stage: "Validate"
    displayName: Validate
    jobs:
      - template: ../.azure-pipelines/jobs/bicep-validate.yml
        parameters:
          # serviceConnection: $(serviceConnection_dev)
          serviceConnection: 'az-adosvc-infrastructure-dev'
          resourceGroupName: $(devResourceGroup)
          environment: dev
          mainTemplate: ./Infrastructure/main.bicep
          additionalArguments:  --parameters ./Infrastructure/parameters.dev.json

  - stage: "DeployDev"
    displayName: "Deploy to dev"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: ../.azure-pipelines/jobs/bicep-deploy.yml
        parameters:
          environment: dev
          serviceConnection: 'az-adosvc-infrastructure-dev'
          resourceGroupName:  $(devResourceGroup)
          mainTemplate: ./Infrastructure/main.bicep
          additionalArguments:  --parameters ./Infrastructure/parameters.dev.json

 
  - stage: "DeployTest"
    displayName: "Deploy to test"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: ../.azure-pipelines/jobs/bicep-deploy.yml
        parameters:
          environment: test
          serviceConnection: $(serviceConnection_test)
          resourceGroupName:  $(testResourceGroup)
          mainTemplate: ./Infrastructure/main.bicep
          additionalArguments:  --parameters ./Infrastructure/parameters.test.json

  
  - stage: "DeployPreprod"
    displayName: "Deploy to preprod"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: ../.azure-pipelines/jobs/bicep-deploy.yml
        parameters:
          environment: preprod
          serviceConnection: $(serviceConnection_preprod)
          resourceGroupName:  $(preprodResourceGroup)
          mainTemplate: ./Infrastructure/main.bicep
          additionalArguments:  --parameters ./Infrastructure/parameters.preprod.json


  - stage: "DeployProd"
    displayName: "Deploy to prod"
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: ../.azure-pipelines/jobs/bicep-deploy.yml
        parameters:
          environment: prod
          serviceConnection: $(serviceConnection_prod)
          resourceGroupName:  $(prodResourceGroup)
          mainTemplate: ./Infrastructure/main.bicep
          additionalArguments:  --parameters ./Infrastructure/parameters.prod.json

